import React, { Component } from 'react';
import { ScrollView, View, StyleSheet, Alert, TouchableOpacity } from 'react-native';
import { Button, Card, FormLabel, Text, Icon } from 'react-native-elements';
import { Formik } from 'formik';
import * as Yup from 'yup';
import { connect } from 'react-redux';
import DatePicker from 'react-native-datepicker';
import ModalSelector from 'react-native-modal-selector';
import UUIDGenerator from 'react-native-uuid-generator';
import moment from 'moment';
import _ from 'lodash';
import { NavigationActions, StackActions } from 'react-navigation';
import PushNotification from 'react-native-push-notification';
import DateTimePicker from 'react-native-modal-datetime-picker';

import {
  addMemo,
  editMemo,
  deleteMemo,
  toggleMemoFetching,
  getCurrentMemo
} from '../../redux/actions';

import Container from '../../components/Container';
import InputForm from '../../components/InputForm';

class AddMemo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      textInputValue: '',
      reminders: [],
      notificationsToDelete: ['', '', '', '', ''],
      isDateTimePickerVisible: false
    };
    this.noteTextInput = null;
  }

  componentDidMount() {
    const { type } = this.props.navigation.state.params;
    const { reminders } = this.props.currentMemo;
    if (this.props.currentMemo.reminders) {
      this.setState({ reminders });
    }
    if (type !== 'edit') {
      this.setState({ reminders: [''], notificationsToDelete: [] });
    }
  }

  onSave = values => {
    const { type } = this.props.navigation.state.params;
    return type === 'edit' ? this.saveEditMemo(values) : this.saveNewMemo(values);
  };

  scheduleNotif(reminders, id, memo, company) {
    const thenum = id.replace(/\D+/g, '').slice(0, 5);
    reminders.map((val, key) => {
      if (moment() < moment(val, 'M/DD/YYYY HH:mm')) {
        const d = new Date();
        d.setTime(Date.parse(val));
        PushNotification.localNotificationSchedule({
          date: d, // in 30 secs
          title: company.name, // (ssoptional)
          message: memo.title, // (required)
          bigText: memo.note, // (optional) default: "message" prop
          subText: 'Expand to read more', // (optional) default: none
          repeatType: 'minute',
          id: `${thenum}${key}`, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
          color: 'blue', // (optional) default: system default
          tag: id, // (optional) add tag to message
          group: company.id // (optional) add group to message
        });
      }
    });
  }

  cancelNotif(id) {
    PushNotification.cancelLocalNotifications({ id });
  }

  saveNewMemo = value => {
    const reminders =
      this.state.reminders[this.state.reminders.length - 1] === ''
        ? _.dropRight(this.state.reminders)
        : this.state.reminders;
    const { id } = this.props.currentCompany;
    UUIDGenerator.getRandomUUID().then(uuid => {
      const memo = {
        id: uuid,
        companyID: id,
        title: value.title,
        note: value.note,
        reminders,
        contact: value.contact,
        createdAt: moment().valueOf(),
        lastModified: ''
      };
      this.props.addMemo(memo, uuid);
      this.scheduleNotif(reminders, id, memo, this.props.currentCompany);
      this.props.navigation.replace('ViewMemo', {
        title: memo.title,
        memoID: memo.id
      });
    });
  };

  saveEditMemo = value => {
    const { id } = this.props.currentMemo;
    const thenum = id.replace(/\D+/g, '').slice(0, 5);

    this.state.notificationsToDelete.map((val, key) => {
      const nId = `${thenum}${key}`;
      console.log('map ID', `${thenum}${key}`);
      this.cancelNotif(nId);
    });
    this.props.toggleMemoFetching(true);
    const lastModified = moment().valueOf();
    const reminders =
      this.state.reminders[this.state.reminders.length - 1] === ''
        ? _.dropRight(this.state.reminders)
        : this.state.reminders;
    this.props.editMemo(value, id, reminders, lastModified);
    this.props.getCurrentMemo(id);
    this.scheduleNotif(reminders, id, value, this.props.currentCompany);
    this.resetStack(this.props.currentCompany);
  };

  deleteCurrentMemo = () => {
    Alert.alert(
      'Are sure you want to Delete?',
      '',
      [
        {
          text: 'Yes',
          onPress: () => {
            this.props.deleteMemo(this.props.currentMemo);
            this.resetStack(this.props.currentCompany);
          }
        },
        { text: 'Cancel', onPress: () => console.log('Cancel Pressed') }
      ],
      { cancelable: true }
    );
  };

  resetStack = currentCompany => {
    this.props.navigation.dispatch(
      StackActions.reset({
        index: 1,
        actions: [
          NavigationActions.navigate({
            routeName: 'Companies'
          }),
          NavigationActions.navigate({
            routeName: 'ViewCompany',
            params: {
              title: currentCompany.name,
              companyID: currentCompany.id,
              type: 'fromEditScreen'
            }
          })
        ]
      })
    );
  };

  _showDateTimePicker = () => this.setState({ isDateTimePickerVisible: true });

  _hideDateTimePicker = () => this.setState({ isDateTimePickerVisible: false });

  _handleDatePicked = date => {
    console.log('A date has been picked: ', date);

    const newArray = this.state.reminders;
    newArray[key] = date;
    this.setState({ reminders: newArray });

    this._hideDateTimePicker();
  };

  _renderDate = key => moment(`${this.state.reminders[key]}`).format('M/DD/YYYY HH:mm');

  render() {
    const { type } = this.props.navigation.state.params;
    const { title, note, contact } = this.props.currentMemo;
    console.log('add memo state', this.state.reminders);
    return (
      <Container style={{ alignItems: 'center' }}>
        <ScrollView style={{ width: '100%' }} keyboardShouldPersistTaps="always">
          <Formik
            initialValues={
              type === 'edit'
                ? {
                    title,
                    note,
                    contact
                  }
                : {
                    title: '',
                    note: '',
                    contact: {}
                  }
            }
            onSubmit={this.onSave}
            validationSchema={Yup.object().shape({
              title: Yup.string().required(),
              note: Yup.string().required()
            })}
            render={({ values, handleSubmit, setFieldValue, errors, touched, setFieldTouched }) => (
              <Card containerStyle={{ width: '92%' }}>
                <ModalSelector
                  keyExtractor={employee => `${employee.id}`}
                  labelExtractor={employee => `${employee.name}`}
                  data={this.props.employees}
                  initValue={
                    _.isEmpty(values.contact) ? 'Select contact' : `${values.contact.name}`
                  }
                  onChange={select => {
                    const info = {
                      id: select.id,
                      name: select.name,
                      phone: select.phone,
                      email: select.email,
                      avatar: select.avatar
                    };
                    setFieldValue('contact', info);
                  }}
                />
                <InputForm
                  label="Memo"
                  placeholder="memo title..."
                  returnKeyType={'next'}
                  onSubmitEditing={() => this.noteTextInput.focus()}
                  value={values.title}
                  onChange={setFieldValue}
                  onTouch={setFieldTouched}
                  name="title"
                  error={touched.title && errors.title}
                />
                <InputForm
                  label="Note"
                  placeholder="note ..."
                  multiline
                  inputRef={input => {
                    this.noteTextInput = input;
                  }}
                  returnKeyType={'done'}
                  value={values.note}
                  onChange={setFieldValue}
                  onTouch={setFieldTouched}
                  name="note"
                  error={touched.note && errors.note}
                />
                <FormLabel>Remider</FormLabel>
                {this.state.reminders.map((v, key) => (
                  <View key={key} style={styles.newReminderContainer}>
                    <View style={{ flex: 1 }}>
                      <TouchableOpacity
                        onPress={this._showDateTimePicker}
                        style={{
                          flexDirection: 'row',
                          alignItems: 'center',
                          justifyContent: 'flex-end',
                          paddingRight: 12
                        }}
                      >
                        <View
                          style={{
                            marginRight: 8,
                            borderBottomWidth: 1,
                            borderBottomColor: 'rgba(0,0,0,.1)'
                          }}
                        >
                          {this.state.reminders[key] ? (
                            <Text>{this._renderDate(key)}</Text>
                          ) : (
                            <Text>M/DD/YYYY HH:mm</Text>
                          )}
                        </View>
                        <Icon name="calendar" type="font-awesome" size={32} color={'#008fff'} />
                      </TouchableOpacity>
                      <DateTimePicker
                        isVisible={this.state.isDateTimePickerVisible}
                        mode="datetime"
                        onCancel={this._hideDateTimePicker}
                        onConfirm={date => {
                          console.log('A date has been picked: ', date);

                          const newArray = this.state.reminders;
                          newArray[key] = date.toISOString();
                          this.setState({ reminders: newArray });

                          this._hideDateTimePicker();
                        }}
                      />
                    </View>
                    <Icon
                      name="minus"
                      type="simple-line-icon"
                      size={28}
                      color={'#b7bbbf'}
                      onPress={() => {
                        const newArray = this.state.reminders;
                        newArray.splice(key, 1);
                        this.setState({ reminders: newArray });
                      }}
                    />
                  </View>
                ))}
                {this.state.reminders.length <= 4 &&
                this.state.reminders[this.state.reminders.length - 1] !== '' ? (
                  <View style={styles.addReminderContainer}>
                    <Text
                      onPress={() => {
                        const newArray = this.state.reminders;
                        newArray.push('');
                        this.setState({ reminders: newArray });
                      }}
                      style={styles.addTextStyle}
                    >
                      Add reminder
                    </Text>
                    <Icon
                      name="plus"
                      type="simple-line-icon"
                      size={28}
                      color={'#b7bbbf'}
                      onPress={() => {
                        const newArray = this.state.reminders;
                        newArray.push('');
                        this.setState({ reminders: newArray });
                      }}
                    />
                  </View>
                ) : null}
                {this.state.reminders.length > 1 ? (
                  <View style={[styles.addReminderContainer, { paddingVertical: 15 }]}>
                    <Text
                      onPress={() => {
                        this.setState({ reminders: [] });
                      }}
                      style={[styles.addTextStyle, { color: 'red' }]}
                    >
                      Delete all reminders
                    </Text>
                    <Icon name="close" type="simple-line-icon" size={28} color={'red'} />
                  </View>
                ) : null}

                <Button title="Save Memo" buttonStyle={styles.button} onPress={handleSubmit} />
                {type === 'edit' ? (
                  <Button
                    title="Delete"
                    buttonStyle={{ backgroundColor: 'red' }}
                    onPress={this.deleteCurrentMemo}
                  />
                ) : null}
              </Card>
            )}
          />
        </ScrollView>
      </Container>
    );
  }
}

const mapStateToProps = state => ({
  currentMemo: state.memo.currentMemo,
  isFetching: state.memo.isFetching,
  currentCompany: state.company.currentCompany,
  employees: state.employee.employees
});

export default connect(
  mapStateToProps,
  { addMemo, editMemo, deleteMemo, toggleMemoFetching, getCurrentMemo }
)(AddMemo);

const styles = StyleSheet.create({
  reminderContainerStyle: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 8,
    paddingRight: 10
  },
  newReminderContainer: {
    justifyContent: 'flex-end',
    flexDirection: 'row',
    marginTop: 10,
    paddingHorizontal: 15
  },
  addReminderContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    marginTop: 10,
    paddingHorizontal: 15
  },
  addTextStyle: {
    fontSize: 16,
    paddingHorizontal: 10,
    color: '#b7bbbf'
  },
  button: {
    marginVertical: 20,
    backgroundColor: '#0082C0',
    marginTop: 40
  }
});
