export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const LISTENERS_UNSUBED = 'LISTENERS_UNSUBED';

export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_CURRENT_COMPANY = 'GET_CURRENT_COMPANY';
export const TOGGLE_COMPANY_FETCHING = 'TOGGLE_COMPANY_FETCHING';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_CURRENT_EMPLOYEE = 'GET_CURRENT_EMPLOYEE';
export const TOGGLE_EMPLOYE_FETCHING = 'TOGGLE_EMPLOYE_FETCHING';

export const GET_MEMOS = 'GET_MEMOS';
export const GET_CURRENT_MEMO = 'GET_CURRENT_MEMO';
export const TOGGLE_MEMO_FETCHING = 'TOGGLE_MEMO_FETCHING';
