export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const LISTENERS_UNSUBED = 'LISTENERS_UNSUBED';
export const ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN';

export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';
export const GET_ALL_MEMOS = 'GET_ALL_MEMOS';
export const ADD_COMPANY = 'ADD_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const TOGGLE_LISTENER_FETCHING = 'TOGGLE_LISTENER_FETCHING';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const GET_MEMOS = 'GET_MEMOS';
export const ADD_MEMO = 'ADD_MEMO';
export const DELETE_MEMO = 'DELETE_MEMO';
